import Footer from "../footer/Footer";
import Navbar from "../navbar/Navbar";
import Head from "next/head";

const Layout = ({ children }) => {
  const pageStyles = {
    backgroundColor: "white", // Replace with your desired background color
  };
  return (
    <div style={pageStyles} >
      <Head>
        <title>AmpereCraft</title>
        <link rel="icon" type="image/png" href="/favicon.png" />
        <meta name="description" content="Generated by tayyaba" />
        <meta name="viewport" content="width=device-width, initial-scale=0.7" />
      </Head>
      <div>
        <Navbar />
        {children}
        <Footer />
      </div>
    </div>
  );
};

export default Layout;
